// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_LVPok9glVmZEhOK5hQBH7lyG5lFqWAw',
    appId: '1:115771809459:web:0a723871319ae8fe81dac6',
    messagingSenderId: '115771809459',
    projectId: 'wefix-16eac',
    authDomain: 'wefix-16eac.firebaseapp.com',
    storageBucket: 'wefix-16eac.firebasestorage.app',
    measurementId: 'G-ZYFEK67V67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzC5293pQvw_z9zTp4JjJtu6ewVK-93Q',
    appId: '1:115771809459:android:80c2c751d0e8b26481dac6',
    messagingSenderId: '115771809459',
    projectId: 'wefix-16eac',
    storageBucket: 'wefix-16eac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTmnH46ulEEyd4syc4ebb6VoQf4dPYrNg',
    appId: '1:115771809459:ios:77954a0d982115cb81dac6',
    messagingSenderId: '115771809459',
    projectId: 'wefix-16eac',
    storageBucket: 'wefix-16eac.firebasestorage.app',
    iosBundleId: 'com.tenderjo.wefixapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTmnH46ulEEyd4syc4ebb6VoQf4dPYrNg',
    appId: '1:115771809459:ios:77954a0d982115cb81dac6',
    messagingSenderId: '115771809459',
    projectId: 'wefix-16eac',
    storageBucket: 'wefix-16eac.firebasestorage.app',
    iosBundleId: 'com.tenderjo.wefixapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_LVPok9glVmZEhOK5hQBH7lyG5lFqWAw',
    appId: '1:115771809459:web:63157e970dafc57881dac6',
    messagingSenderId: '115771809459',
    projectId: 'wefix-16eac',
    authDomain: 'wefix-16eac.firebaseapp.com',
    storageBucket: 'wefix-16eac.firebasestorage.app',
    measurementId: 'G-1PZPKX799Q',
  );
}
